### PR TITLE
Remove FCC soldering part

### PR DESCRIPTION
**Pull request by pashutk**
I think that FCC hand soldering part isn't necessary anymore because today (22 Apr 2021) I placed an order and not only C262294 was found and placed correctly, but also my order did pass the review.

Screenshot 2021-04-22 at 20 19 53
Screenshot 2021-04-22 at 20 19 58

You can check it by yourself, try to place a new order. I'll update PR if there are problems with mine.

### CODE REVIEW

**Comment by Nicell** [comment]
Hi @pashutk. Thanks for pointing this out. However, it seems that the FFC connector is misplaced in your screenshot meaning there's probably a mismatch between my footprint and the footprint that JLC expects. We'll probably need that updated so that it's assembled properly every time.

**Comment by pashutk** [comment]
You're right, I've missed it. But look, after DFM Analysis stage they've corrected part placement.

Screenshot 2021-04-23 at 12 43 29
Screenshot 2021-04-23 at 12 43 07

Now it's seems okay. Anyway it's probably a good idea to fix the mismatch in footprint. Unfortunately I can't help with this, my kicad skills are pretty low. Would you consider to fix that by yourself, please?

**Comment by Nicell** [comment]
That's good that they corrected it for you. We probably shouldn't rely on this though. I'll see if I can fix this up later this evening.

**Review by Nicell — APPROVED** [review]
@pashutk Thanks for bringing this to my attention. I've updated the position file to match JLC's assembly now.

**Pull request merged**
